### ISSUE TITLE
Animationer

### ISSUE THREAD

**Issue by YodaZen** [martinersej/LeuxServerSelector#3]
Gøre så man kan lave text animationer, hvis man gerne vil have noget til at ændre sig med tiden ;)

**Comment by martinpugdal** [comment]
> Gøre så man kan lave text animationer, hvis man gerne vil have noget til at ændre sig med tiden ;)

Må gerne lige uddybes lidt mere eller vis et eksempel på det.

**Comment by YodaZen** [comment]
MyAnimation1:
  change-interval: 100
  texts:
  - '&d-&3--------------'
  - '&3-&d-&3-------------'
  - '&3--&d-&3------------'
  - '&3---&d-&3-----------'
  - '&3----&d-&3----------'
  - '&3-----&d-&3---------'
  - '&3------&d-&3--------'
  - '&3-------&d-&3-------'
  - '&3--------&d-&3------'
  - '&3---------&d-&3-----'
  - '&3----------&d-&3----'
  - '&3-----------&d-&3---'
  - '&3------------&d-&3--'
  - '&3-------------&d-&3-'
  - '&3--------------&d-'
  - '&3-------------&d-&3-'
  - '&3------------&d-&3--'
  - '&3-----------&d-&3---'
  - '&3----------&d-&3----'
  - '&3---------&d-&3-----'
  - '&3--------&d-&3------'
  - '&3-------&d-&3-------'
  - '&3------&d-&3--------'
  - '&3-----&d-&3---------'
  - '&3----&d-&3----------'
  - '&3---&d-&3-----------'
  - '&3--&d-&3------------'
  - '&3-&d-&3-------------'
  - '&d-&3--------------'


Altså ligesom den her :)


Så for at få det ind og stå på item'ets lore eller titel, så er det bare "%animation::MyAnimation1%"

**Comment by martinpugdal** [comment]
> MyAnimation1:
>   change-interval: 100
>   texts:
>   - '&d-&3--------------'
>   - '&3-&d-&3-------------'
>   - '&3--&d-&3------------'
>   - '&3---&d-&3-----------'
>   - '&3----&d-&3----------'
>   - '&3-----&d-&3---------'
>   - '&3------&d-&3--------'
>   - '&3-------&d-&3-------'
>   - '&3--------&d-&3------'
>   - '&3---------&d-&3-----'
>   - '&3----------&d-&3----'
>   - '&3-----------&d-&3---'
>   - '&3------------&d-&3--'
>   - '&3-------------&d-&3-'
>   - '&3--------------&d-'
>   - '&3-------------&d-&3-'
>   - '&3------------&d-&3--'
>   - '&3-----------&d-&3---'
>   - '&3----------&d-&3----'
>   - '&3---------&d-&3-----'
>   - '&3--------&d-&3------'
>   - '&3-------&d-&3-------'
>   - '&3------&d-&3--------'
>   - '&3-----&d-&3---------'
>   - '&3----&d-&3----------'
>   - '&3---&d-&3-----------'
>   - '&3--&d-&3------------'
>   - '&3-&d-&3-------------'
>   - '&d-&3--------------'
> 
> 
> Altså ligesom den her :)
> 
> 
> Så for at få det ind og stå på item'ets lore eller titel, så er det bare "%animation::MyAnimation1%"

Lyder som en god idé.
Kan godt tilføje det på et tidspunkt.

**Comment by martinpugdal** [comment]
wont be added, this plugin isn't being maintained anymore.
